export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { Inter as FontSans } from 'next/font/google'

import "../globals.css"

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
